title: Rohith Kumar Kaza
description: Computer Science Graduate at Rice University
theme: jekyll-theme-minimal

contact:
  email: rk121@rice.edu
  phone: "+1 (713)-550-0979"
  linkedin: "https://www.linkedin.com/in/rohith-kumar-kaza"
  location: "Houston, TX 77054"

education:
  - institution: "Rice University, Houston, TX, USA"
    degree: "Master’s in Computer Science (Specialization in Artificial Intelligence)"
    duration: "August 2024 - December 2025"
  - institution: "Koneru Lakshmaiah (KL) University, Guntur, India"
    degree: "Bachelor of Technology in Computer Science and Engineering"
    duration: "June 2018 - March 2022"
    gpa: "9.12/10"

experience:
  - role: "Software Engineer (Python Developer)"
    company: "Mitsogo, Chennai, India"
    duration: "August 2023 – July 2024"
    responsibilities:
      - "Developed and integrated new features and RESTful APIs using Django and AngularJS."
      - "Optimized backend logic and database structures, improving response times by 20%."
      - "Collaborated with cross-functional teams, reducing post-deployment issues by 25%."

  - role: "Software Development Engineer"
    company: "Rudderstack, Kolkata, India"
    duration: "February 2022 – January 2023"
    responsibilities:
      - "Developed scalable REST APIs using Node.js and JavaScript."
      - "Achieved a 98% deployment success rate for 16 SaaS platforms."

skills:
  - "Django"
  - "Flask"
  - "AngularJS"
  - "Python"
  - "JavaScript"
  - "SQL"
  - "Docker"
  - "Kubernetes"
  - "AI"
  - "Machine Learning"

projects:
  - name: "Real-Time Analytics on Streaming Data"
    description: "Implemented a sentiment analysis tool using NLP and Python, achieving 90% accuracy."
  - name: "Arogya Sukha Web Application"
    description: "Centralized web app for patient records, boosting user engagement with health articles."

achievements:
  - "1st Prize in National Level Coding Competition (#Include), February 2019"
  - "Technical Coordinator for Samyak, orchestrating 10+ technical events, October 2019"
  - "Volunteer at APTA Medical Camp, March 2019"
